import type { Metadata } from "next";
import ThemeRegistry from "./ThemeRegistry";
import NavBar from "@/components/NavBar";
import "./index.css";
import { Container } from "@mui/joy";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ThemeRegistry options={{ key: "joy" }}>
          <NavBar />
          <Container sx={{ marginLeft: { sm: "64px", md: undefined}, width: 'calc(100% - 64px)', margin: { lg: 'auto' } }}>{children}</Container>
        </ThemeRegistry>
      </body>
    </html>
  );
}
